
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heiqi?user=heiqi&password=heiqi2023&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 16
      minimum-idle: 2
      idle-timeout: 10000
  data:
    redis:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      database: 0
      host:  localhost
      connect-timeout: 10000
      port: 6379

auth:
  # JWT认证加密私钥(Base64加密)
  encryptJWTKey: YmFvaG9uZ2tlamkyMDIxMTAyNA==

server:
  port: 10000
